// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package queries

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (owner_id, kind, name) 
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, owner_id, kind, name
`

type CreateAccountParams struct {
	OwnerID int32
	Kind    AccountType
	Name    string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.OwnerID, arg.Kind, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.Kind,
		&i.Name,
	)
	return i, err
}
