// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountType string

const (
	AccountTypeCredit AccountType = "credit"
	AccountTypeDebit  AccountType = "debit"
	AccountTypeCash   AccountType = "cash"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type Account struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	OwnerID   int32
	Kind      AccountType
	Name      string
}

type Category struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	OwnerID   int32
	Name      string
	Color     string
	Icon      string
}

type Transaction struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Amount     int32
	AccountID  uuid.UUID
	CategoryID int32
	Title      string
	Date       time.Time
	Attachment sql.NullString
	Note       sql.NullString
}

type User struct {
	ID             int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	HashedPassword string
	Name           string
}
