// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package database

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (type, name) 
VALUES ($1, $2)
RETURNING id, type, name
`

type CreateAccountParams struct {
	Type AccountType `json:"type"`
	Name string      `json:"name"`
}

type CreateAccountRow struct {
	ID   int32       `json:"id"`
	Type AccountType `json:"type"`
	Name string      `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Type, arg.Name)
	var i CreateAccountRow
	err := row.Scan(&i.ID, &i.Type, &i.Name)
	return i, err
}
