// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package store

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (type, name, user_id, balance_cents) 
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, type, name, balance_cents, version, user_id
`

type CreateAccountParams struct {
	Type         AccountType `json:"type"`
	Name         string      `json:"name"`
	UserID       int32       `json:"user_id"`
	BalanceCents int64       `json:"balance_cents"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Type,
		arg.Name,
		arg.UserID,
		arg.BalanceCents,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.BalanceCents,
		&i.Version,
		&i.UserID,
	)
	return i, err
}

const deleteAccountById = `-- name: DeleteAccountById :execresult
DELETE FROM accounts
WHERE id = $1 AND user_id = $2
`

type DeleteAccountByIdParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteAccountById(ctx context.Context, arg DeleteAccountByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAccountById, arg.ID, arg.UserID)
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, created_at, updated_at, type, name, balance_cents, version, user_id FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.BalanceCents,
		&i.Version,
		&i.UserID,
	)
	return i, err
}

const getAccountSumBalance = `-- name: GetAccountSumBalance :one
SELECT accounts.name, SUM(transactions.amount_cents) AS balance
FROM transactions
RIGHT JOIN accounts ON transactions.account_id = accounts.id
WHERE account_id = $1 AND user_id = $2
GROUP BY accounts.id
`

type GetAccountSumBalanceParams struct {
	AccountID int32 `json:"account_id"`
	UserID    int32 `json:"user_id"`
}

type GetAccountSumBalanceRow struct {
	Name    string `json:"name"`
	Balance int64  `json:"balance"`
}

func (q *Queries) GetAccountSumBalance(ctx context.Context, arg GetAccountSumBalanceParams) (GetAccountSumBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountSumBalance, arg.AccountID, arg.UserID)
	var i GetAccountSumBalanceRow
	err := row.Scan(&i.Name, &i.Balance)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, created_at, updated_at, type, name, balance_cents, version, user_id FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.Name,
			&i.BalanceCents,
			&i.Version,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccounts = `-- name: GetUserAccounts :many
SELECT id, created_at, updated_at, type, name, balance_cents, version, user_id FROM accounts
WHERE user_id = $1
`

func (q *Queries) GetUserAccounts(ctx context.Context, userID int32) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getUserAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.Name,
			&i.BalanceCents,
			&i.Version,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountById = `-- name: UpdateAccountById :execresult
UPDATE accounts
SET name = $1, type = $2, version = version + 1, updated_at = NOW()
WHERE id = $3 AND user_id = $4 AND version = $5
`

type UpdateAccountByIdParams struct {
	Name    string      `json:"name"`
	Type    AccountType `json:"type"`
	ID      int32       `json:"id"`
	UserID  int32       `json:"user_id"`
	Version int32       `json:"-"`
}

func (q *Queries) UpdateAccountById(ctx context.Context, arg UpdateAccountByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAccountById,
		arg.Name,
		arg.Type,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE accounts
SET balance_cents = balance_cents + $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING balance_cents
`

type UpdateBalanceParams struct {
	BalanceCents int64 `json:"balance_cents"`
	ID           int32 `json:"id"`
	UserID       int32 `json:"user_id"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateBalance, arg.BalanceCents, arg.ID, arg.UserID)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}
