// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package store

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (type, name) 
VALUES ($1, $2)
RETURNING id, created_at, updated_at, type, name, balance_cents, version, user_id
`

type CreateAccountParams struct {
	Type AccountType `json:"type"`
	Name string      `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Type, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.BalanceCents,
		&i.Version,
		&i.UserID,
	)
	return i, err
}

const deleteAccountById = `-- name: DeleteAccountById :execresult
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccountById(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAccountById, id)
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, created_at, updated_at, type, name, balance_cents, version, user_id FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.BalanceCents,
		&i.Version,
		&i.UserID,
	)
	return i, err
}

const getAccountSumBalance = `-- name: GetAccountSumBalance :one
SELECT accounts.name, SUM(transactions.amount_cents) AS balance
FROM transactions
RIGHT JOIN accounts ON transactions.account_id = accounts.id
WHERE account_id = $1
GROUP BY accounts.id
`

type GetAccountSumBalanceRow struct {
	Name    string `json:"name"`
	Balance int64  `json:"balance"`
}

func (q *Queries) GetAccountSumBalance(ctx context.Context, accountID int32) (GetAccountSumBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountSumBalance, accountID)
	var i GetAccountSumBalanceRow
	err := row.Scan(&i.Name, &i.Balance)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, created_at, updated_at, type, name, balance_cents, version, user_id FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.Name,
			&i.BalanceCents,
			&i.Version,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountById = `-- name: UpdateAccountById :execresult
UPDATE accounts
SET name = $1, type = $2, version = version + 1
WHERE id = $3 AND version = $4
`

type UpdateAccountByIdParams struct {
	Name    string      `json:"name"`
	Type    AccountType `json:"type"`
	ID      int32       `json:"id"`
	Version int32       `json:"-"`
}

func (q *Queries) UpdateAccountById(ctx context.Context, arg UpdateAccountByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAccountById,
		arg.Name,
		arg.Type,
		arg.ID,
		arg.Version,
	)
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE accounts
SET balance_cents = balance_cents + $2
WHERE id = $1
RETURNING balance_cents
`

type UpdateBalanceParams struct {
	ID           int32 `json:"id"`
	BalanceCents int64 `json:"balance_cents"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateBalance, arg.ID, arg.BalanceCents)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}
