// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccountById(ctx context.Context, arg DeleteAccountByIdParams) (sql.Result, error)
	DeleteCategoryById(ctx context.Context, id int32) (sql.Result, error)
	DeleteTransactionByID(ctx context.Context, arg DeleteTransactionByIDParams) (sql.Result, error)
	DeleteUserById(ctx context.Context, id int32) (sql.Result, error)
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetAccountSumBalance(ctx context.Context, arg GetAccountSumBalanceParams) (GetAccountSumBalanceRow, error)
	GetAllAccounts(ctx context.Context) ([]Account, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllTransactions(ctx context.Context, userID int32) ([]GetAllTransactionsRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error)
	GetTransactionsByAccountID(ctx context.Context, arg GetTransactionsByAccountIDParams) ([]GetTransactionsByAccountIDRow, error)
	GetUserAccounts(ctx context.Context, userID int32) ([]Account, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserFromToken(ctx context.Context, arg GetUserFromTokenParams) (GetUserFromTokenRow, error)
	InsertInitialCategory(ctx context.Context) error
	UpdateAccountById(ctx context.Context, arg UpdateAccountByIdParams) (sql.Result, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (int64, error)
	UpdateCategoryById(ctx context.Context, arg UpdateCategoryByIdParams) (sql.Result, error)
	UpdateTransactionById(ctx context.Context, arg UpdateTransactionByIdParams) (sql.Result, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
