// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tokens.sql

package store

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (hash, user_id, expiry)
VALUES ($1, $2, $3)
RETURNING hash, user_id, expiry
`

type CreateTokenParams struct {
	Hash   []byte    `json:"hash"`
	UserID int32     `json:"user_id"`
	Expiry time.Time `json:"expiry"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.Hash, arg.UserID, arg.Expiry)
	var i Token
	err := row.Scan(&i.Hash, &i.UserID, &i.Expiry)
	return i, err
}
