// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, amount_cents, category_id, title, attachment, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, amount_cents, account_id, category_id, title, date, attachment, note, version
`

type CreateTransactionParams struct {
	AccountID   int32  `json:"account_id"`
	AmountCents int64  `json:"amount_cents"`
	CategoryID  int32  `json:"category_id"`
	Title       string `json:"title"`
	Attachment  string `json:"attachment"`
	Note        string `json:"note"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.AccountID,
		arg.AmountCents,
		arg.CategoryID,
		arg.Title,
		arg.Attachment,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmountCents,
		&i.AccountID,
		&i.CategoryID,
		&i.Title,
		&i.Date,
		&i.Attachment,
		&i.Note,
		&i.Version,
	)
	return i, err
}

const deleteTransactionByID = `-- name: DeleteTransactionByID :one
DELETE FROM transactions
USING accounts
WHERE transactions.account_id = accounts.id
  AND transactions.id = $1
  AND accounts.user_id = $2
RETURNING transactions.id, transactions.created_at, transactions.updated_at, transactions.amount_cents, transactions.account_id, transactions.category_id, transactions.title, transactions.date, transactions.attachment, transactions.note, transactions.version
`

type DeleteTransactionByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type DeleteTransactionByIDRow struct {
	Transaction Transaction `json:"transaction"`
}

func (q *Queries) DeleteTransactionByID(ctx context.Context, arg DeleteTransactionByIDParams) (DeleteTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, deleteTransactionByID, arg.ID, arg.UserID)
	var i DeleteTransactionByIDRow
	err := row.Scan(
		&i.Transaction.ID,
		&i.Transaction.CreatedAt,
		&i.Transaction.UpdatedAt,
		&i.Transaction.AmountCents,
		&i.Transaction.AccountID,
		&i.Transaction.CategoryID,
		&i.Transaction.Title,
		&i.Transaction.Date,
		&i.Transaction.Attachment,
		&i.Transaction.Note,
		&i.Transaction.Version,
	)
	return i, err
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT transactions.id, transactions.created_at, transactions.updated_at, transactions.amount_cents, transactions.account_id, transactions.category_id, transactions.title, transactions.date, transactions.attachment, transactions.note, transactions.version FROM transactions
INNER JOIN accounts ON transactions.account_id = accounts.id
WHERE accounts.user_id = $1
`

type GetAllTransactionsRow struct {
	Transaction Transaction `json:"transaction"`
}

func (q *Queries) GetAllTransactions(ctx context.Context, userID int32) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTransactionsRow
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.AmountCents,
			&i.Transaction.AccountID,
			&i.Transaction.CategoryID,
			&i.Transaction.Title,
			&i.Transaction.Date,
			&i.Transaction.Attachment,
			&i.Transaction.Note,
			&i.Transaction.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT transactions.id, transactions.created_at, transactions.updated_at, transactions.amount_cents, transactions.account_id, transactions.category_id, transactions.title, transactions.date, transactions.attachment, transactions.note, transactions.version FROM transactions
INNER JOIN accounts ON transactions.account_id = accounts.id
WHERE transactions.id = $1 AND accounts.user_id = $2
`

type GetTransactionByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetTransactionByIDRow struct {
	Transaction Transaction `json:"transaction"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.Transaction.ID,
		&i.Transaction.CreatedAt,
		&i.Transaction.UpdatedAt,
		&i.Transaction.AmountCents,
		&i.Transaction.AccountID,
		&i.Transaction.CategoryID,
		&i.Transaction.Title,
		&i.Transaction.Date,
		&i.Transaction.Attachment,
		&i.Transaction.Note,
		&i.Transaction.Version,
	)
	return i, err
}

const getTransactionsByAccountID = `-- name: GetTransactionsByAccountID :many
SELECT transactions.id, transactions.created_at, transactions.updated_at, transactions.amount_cents, transactions.account_id, transactions.category_id, transactions.title, transactions.date, transactions.attachment, transactions.note, transactions.version FROM transactions
INNER JOIN accounts ON transactions.account_id = accounts.id
WHERE transactions.account_id = $1 AND accounts.user_id = $2
`

type GetTransactionsByAccountIDParams struct {
	AccountID int32 `json:"account_id"`
	UserID    int32 `json:"user_id"`
}

type GetTransactionsByAccountIDRow struct {
	Transaction Transaction `json:"transaction"`
}

func (q *Queries) GetTransactionsByAccountID(ctx context.Context, arg GetTransactionsByAccountIDParams) ([]GetTransactionsByAccountIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByAccountID, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByAccountIDRow
	for rows.Next() {
		var i GetTransactionsByAccountIDRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.AmountCents,
			&i.Transaction.AccountID,
			&i.Transaction.CategoryID,
			&i.Transaction.Title,
			&i.Transaction.Date,
			&i.Transaction.Attachment,
			&i.Transaction.Note,
			&i.Transaction.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionById = `-- name: UpdateTransactionById :execresult
UPDATE transactions
SET amount_cents = $1,
    account_id = $2,
    category_id = $3,
    title = $4,
    date = $5,
    attachment = $6,
    note = $7,
    version = transactions.version + 1,
    updated_at = NOW()
FROM accounts
WHERE transactions.account_id = accounts.id
  AND transactions.id = $8
  AND accounts.user_id = $9
  AND transactions.version = $10
`

type UpdateTransactionByIdParams struct {
	AmountCents int64     `json:"amount_cents"`
	AccountID   int32     `json:"account_id"`
	CategoryID  int32     `json:"category_id"`
	Title       string    `json:"title"`
	Date        time.Time `json:"date"`
	Attachment  string    `json:"attachment"`
	Note        string    `json:"note"`
	ID          int32     `json:"id"`
	UserID      int32     `json:"user_id"`
	Version     int32     `json:"-"`
}

func (q *Queries) UpdateTransactionById(ctx context.Context, arg UpdateTransactionByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTransactionById,
		arg.AmountCents,
		arg.AccountID,
		arg.CategoryID,
		arg.Title,
		arg.Date,
		arg.Attachment,
		arg.Note,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
}
