// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name, password_hash) 
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, version, username, name, password_hash
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Name         string `json:"name"`
	PasswordHash []byte `json:"-"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :execresult
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserById, id)
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, created_at, updated_at, version, username, name, password_hash FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.Username,
			&i.Name,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, version, username, name, password_hash FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, version, username, name, password_hash FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const getUserFromToken = `-- name: GetUserFromToken :one
SELECT users.id, users.username 
FROM users
INNER JOIN tokens
ON users.id = tokens.user_id
WHERE tokens.hash = $1
AND tokens.expiry > $2
`

type GetUserFromTokenParams struct {
	Hash   []byte    `json:"hash"`
	Expiry time.Time `json:"expiry"`
}

type GetUserFromTokenRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) GetUserFromToken(ctx context.Context, arg GetUserFromTokenParams) (GetUserFromTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromToken, arg.Hash, arg.Expiry)
	var i GetUserFromTokenRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const updateUserById = `-- name: UpdateUserById :execresult
UPDATE users
SET name = $1, password_hash = $2, version = version + 1
WHERE id = $3 AND version = $4
`

type UpdateUserByIdParams struct {
	Name         string `json:"name"`
	PasswordHash []byte `json:"-"`
	ID           int32  `json:"id"`
	Version      int32  `json:"-"`
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserById,
		arg.Name,
		arg.PasswordHash,
		arg.ID,
		arg.Version,
	)
}
